FROM python:3.8-slim-buster

ENV PYTHONUNBUFFERED 1

RUN pip3 install ansible=={{ansible_latest_version}} docker "pywinrm>=0.3.0"

ENV ANSIBLE_LOCAL_TEMP=/tmp

RUN useradd -m ansible -g root

COPY entrypoint.sh /usr/bin/entrypoint

RUN chmod 755 /usr/bin/entrypoint

WORKDIR /home/ansible

USER ansible

ENTRYPOINT ["/usr/bin/entrypoint"]