version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout # check out the code in the project directory
      - run:
          command: |  # use pipenv to install dependencies
            sudo apt-get install -y python3
            python3 --version
            sudo pip3 install ansible
            sudo pip3 install --upgrade setuptools

#deployment:
#  prod:
#    branch: master
#    commands:
#      - ansible-playbook -i inventory create-docker-image.yml