version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: "Set Python Version"
          command: pyenv global 3.7.0
      - run:
          name: install ansible
          command: |  # use pipenv to install dependencies
            python  --version
            sudo pip install ansible
            sudo pip install docker
      - run: 
          name: Execute Ansible Playbook
          command: sudo ansible-playbook -i inventory create-docker-image.yml