version: 2.1

machine:
  services:
    - docker
  python:
    version: 3.6.0

dependencies:
  pre:
    - pip install ansible
    - pip install --upgrade setuptools

deployment:
  prod:
    branch: master
    commands:
      - ansible-playbook -i inventory create-docker-image.yml