version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: "Set Python Version"
          command: pyenv global 3.7.0
      - run:
          name: Install Ansible
          command: |  # use pipenv to install dependencies
            python  --version
            pip install ansible
            pip install docker
      - run:
          name: Execute Ansible Playbook
          command: ansible-playbook -i inventory create-docker-image.yml
      - run: 
          name: Publish Image to Docker Hub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker images | grep exsketrix/ansible | awk '{print $2}'