version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command

dependencies:
  pre:
    - pip install ansible
    - pip install --upgrade setuptools

#deployment:
#  prod:
#    branch: master
#    commands:
#      - ansible-playbook -i inventory create-docker-image.yml