version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: "Set Python Version"
          command: pyenv global 3.7.0
      - run:
          name: Install Ansible
          command: |  # use pipenv to install dependencies
            python  --version
            pip install ansible
            pip install docker
      - run:
          name: Execute Ansible Playbook
          command: ansible-playbook -i inventory create-docker-image.yml
      - run:
          name: Execute Molecule and Testinfra against built Image
          command: |
            cd roles/${CIRCLE_PROJECT_REPONAME}-role
            docker run --rm -it -v "$(pwd)":/tmp/$(basename "${PWD}"):rw -v /var/run/docker.sock:/var/run/docker.sock -w /tmp/$(basename "${PWD}") quay.io/ansible/molecule:3.0.3 molecule test
# TODO: Add in test step to execute molecule before publishing and also try a dummy playbook execution
      - run:
          name: Publish to Dockerhub
          command: |
            export DOCKER_CLI_EXPERIMENTAL=enabled
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
            DOCKER_TAG=`docker images | egrep ^${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME} | awk '{print $2}'`
            TAG_NOT_EXISTS=`docker manifest inspect ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}:$DOCKER_TAG > /dev/null; echo $?`
            if [[ ${TAG_NOT_EXISTS} -eq 1 ]] ; then
              docker tag ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}:$DOCKER_TAG ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}:latest
              docker push ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}:latest
              docker push ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}:$DOCKER_TAG
            fi