version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: "Set Python Version"
          command: pyenv global 3.7.0
      #- run:
      #    name: Install Ansible
      #    command: |  # use pipenv to install dependencies
      #      python  --version
      #      pip install ansible
      #      pip install docker
      #- run:
      #    name: Execute Ansible Playbook
      #    command: ansible-playbook -i inventory create-docker-image.yml
# TODO: Add in test step to execute molecule before publishing and also try a dummy playbook execution
# TODO: Make publishing conditional on whether tag already exists in repository
      - run:
          name: Check whether tag build already exists in dockerhub
          command: |
            export DOCKER_CLI_EXPERIMENTAL=enabled
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
            #DOCKER_TAG=`docker images | grep ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME} | awk '{print $2}'`
            DOCKER_TAG=3.9.9
            TAG_NOT_EXISTS=`docker manifest inspect ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}:$DOCKER_TAG > /dev/null; echo $?`
            if [ $TAG_NOT_EXISTS ] ; then
              echo the tag doesn't exist
            fi
      #- run: 
      #    name: Publish Image to Docker Hub
      #    command: |
      #      DOCKER_TAG=`docker images | grep ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME} | awk '{print $2}'`
      #      docker tag ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}:$DOCKER_TAG ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}:latest
      #      docker push ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}:latest
      #      docker push ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}:$DOCKER_TAG