---

- name: Run Hello World Cmd
  shell: echo hello world
  args:
    warn: no
  failed_when: False
  changed_when: False
  register: hello_cmd

- name: Output result of Hello World Cmd Execution
  debug:
    msg: "{{ hello_cmd.stdout }}"

- name: Test executing hello world docker image
  docker_container:
    name: hello_world
    image: hello-world
    detach: false
    recreate: true